export { default as Phoneicon } from './svgs/phone-icon.svg'
export { default as Phonelineicon } from './svgs/phone-line-icon.svg'
export { default as Emailicon } from './svgs/email-icon.svg'
export { default as Emaillineicon } from './svgs/email-line-icon.svg'
export { default as Locationicon } from './svgs/location-icon.svg'
export { default as Burgericon } from './svgs/burger-icon.svg'
export { default as Beststaricon } from './svgs/best-stars-icon.svg'
export { default as Compareicon } from './svgs/compare-icon.svg'
export { default as Globeicon } from './svgs/globe-icon.svg'
export { default as Baricon } from './svgs/bar-icon.svg'
export { default as Searchicon } from './svgs/search-icon.svg'
export { default as Adjustmenticon } from './svgs/adjustment-icon.svg'
export { default as Usericon } from './svgs/user-icon.svg'
export { default as Hearticon } from './svgs/heart-icon.svg'
export { default as Shoppingbagicon } from './svgs/shopping-icon.svg'
export { default as Compassicon } from './svgs/compass-icon.svg'
export { default as Staricon } from './svgs/star-icon.svg'
export { default as Mobileicon } from './svgs/mobile-icon.svg'
export { default as Arrowicon } from './svgs/arrow-icon.svg'
export { default as Anglelefticon } from './svgs/angle-left-icon.svg'
export { default as Anglerighticon } from './svgs/angle-right-icon.svg'
 
 