import type { Metadata } from "next";
import { Nunito, DM_Sans } from 'next/font/google' 
import "./globals.css";


const nunito = Nunito({
  subsets: ['latin'],
  variable: "--nunito",
  display: 'swap',
})

const dmsans = DM_Sans({
  subsets: ['latin'],
  variable: "--dmsans",
  display: 'swap',
})

 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.variable} ${dmsans.variable}`}>
      <body className={`antialiased`} >
        {children}
      </body>
    </html>
  );
}
